name: PR validation CldapCore
on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  call-workflow:
    name: Build and package CldapCore
    uses:  ./.github/workflows/build.yml
