name: Release CldapCore

on:
  push:
    branches:
      - main
      - releases/**
  workflow_dispatch:

 jobs:
  call-workflow:
    name: Build and package CldapCore
    uses: ./.github/workflows/build.yml
